qt5: Fix build with WITH_X11=FALSE
Otherwise fails with

".../x86_64-pc-linux-gnu/bin/ld.bfd:
.../plasma-integration-6.7.90/qt5/src/platformtheme/kdeplatformtheme.cpp:678:(.text+0xe8b):
undefined reference to `X11Integration::setWindowProperty(QWindow*, QByteArray const&, QByteArray const&)'"

(cherry picked from commit 03ae41d21d2bdeb7f08067df9f41ace18afdcb5a)